version: "3.8"

services:
  postgres:
    container_name: fast-feet-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=fast-feet
      - PG_DATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: fast-feet-cache
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/data
