name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: find-a-friend

      cache:
        image: bitnami/redis
        ports:
          - 6379:6379
        env:
          ALLOW_EMPTY_PASSWORD: yes

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci
      - run: npm run ci:gen-jwt-keys

      - run: npm run test:e2e
        env:
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/fast-feet?schema=public"
          CLOUDFARE_R2_ACCOUNT_ID: ${{ secrets.CLOUDFARE_R2_ACCOUNT_ID }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_STORAGE_API_KEY: ${{ secrets.AWS_STORAGE_API_KEY }}
          AWS_STORAGE_SECRET_API_KEY: ${{ secrets.AWS_STORAGE_SECRET_API_KEY }}
